### ISSUE TITLE
RAT Stub Won't Open

### ISSUE THREAD

**Issue by Zirzux** [NullCode13/NullRAT#19]
Yes this is nullrat v2 i tried latest also nothing.

Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\NullRAT-v2\RAT.py", line 1, in <module>
    import os, subprocess, re, discord
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39-32\lib\site-packages\discord\__init__.py", line 25, in <module>
    from .client import Client
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39-32\lib\site-packages\discord\client.py", line 53, in <module>
    from .webhook import Webhook
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39-32\lib\site-packages\discord\webhook\__init__.py", line 12, in <module>
    from .async_ import *
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39-32\lib\site-packages\discord\webhook\async_.py", line 49, in <module>
    from ..channel import PartialMessageable
ImportError: cannot import name 'PartialMessageable' from 'discord.channel' (C:\Users\Administrator\AppData\Local\Programs\Python\Python39-32\lib\site-packages\discord\channel.py)
>>>

**Comment by serialame** [comment]
Have u checked all this
https://github.com/NullCode1337/NullRAT#preparation

Otherwise I would remove all your modules and install only the ones for the rat again

**Comment by NullCode1337** [comment]
^^

i think there's some weird discord lib installed on your pc
uninstall all discord api wrappers, and run dependencies installer again

**Comment by NullCode1337** [comment]
closed because no replies from op
