### ISSUE TITLE
[Inactive] Failed to execute script 'RAT' due to unhandled exception

### ISSUE THREAD

**Issue by mrlolua19** [NullCode13/NullRAT#60]
Traceback (most recent call last):
  File "RAT.py", line 193, in <module>
  File "disnake\ext\commands\common_bot_base.py", line 473, in load_extension
disnake.ext.commands.errors.ExtensionNotFound: Extension 'rawTokens' could not be loaded.

**Comment by NullCode1337** [comment]
is this the dev version from github, or stable release

**Comment by NullCode1337** [comment]
closing due to inactivity
