### ISSUE TITLE
[Solved] Unable to Run Compiled version

### ISSUE THREAD

**Issue by Proxy3200** [NullCode13/NullRAT#64]
Hi I am Unable to run the RAT after compiling it . I am getting a error

"Traceback (most recent call last):
  File "<dist\obf\RAT.py>", line 3, in <module>
  File "<frozen RAT>", line 198, in <module>
  File "disnake\client.py", line 1128, in run
  File "disnake\client.py", line 1107, in runner
  File "disnake\client.py", line 1069, in start
  File "disnake\client.py", line 945, in connect
  File "disnake\gateway.py", line 735, in poll_event
disnake.errors.ConnectionClosed: Shard ID None WebSocket closed with 4004: Authentication failed"

**Comment by NullCode1337** [comment]
let me see

**Comment by NullCode1337** [comment]
![image](https://github.com/NullCode1337/NullRAT/assets/70959549/5f9a7c79-c1c9-4844-9ee4-f22ca0ee971d)

literally just downloaded the latest release and compiled, working fine
have you checked your token?
